/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlmoxarifadoRouteImport } from './routes/almoxarifado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChaoDeFabricaRouteImport } from './routes/chao-de-fabrica'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EnergiaRouteImport } from './routes/energia'
import { Route as IaRouteImport } from './routes/ia'
import { Route as IiotRouteImport } from './routes/iiot'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as MesRouteImport } from './routes/mes'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ScadaRouteImport } from './routes/scada'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoRoute = AlmoxarifadoRouteImport.update({
  id: '/almoxarifado',
  path: '/almoxarifado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaoDeFabricaRoute = ChaoDeFabricaRouteImport.update({
  id: '/chao-de-fabrica',
  path: '/chao-de-fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaRoute = EnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IiotRoute = IiotRouteImport.update({
  id: '/iiot',
  path: '/iiot',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRoute = MesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ScadaRoute = ScadaRouteImport.update({
  id: '/scada',
  path: '/scada',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/auth': typeof AuthRoute
  '/chao-de-fabrica': typeof ChaoDeFabricaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/energia': typeof EnergiaRoute
  '/ia': typeof IaRoute
  '/iiot': typeof IiotRoute
  '/manutencao': typeof ManutencaoRoute
  '/mes': typeof MesRoute
  '/qualidade': typeof QualidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/scada': typeof ScadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/auth': typeof AuthRoute
  '/chao-de-fabrica': typeof ChaoDeFabricaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/energia': typeof EnergiaRoute
  '/ia': typeof IaRoute
  '/iiot': typeof IiotRoute
  '/manutencao': typeof ManutencaoRoute
  '/mes': typeof MesRoute
  '/qualidade': typeof QualidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/scada': typeof ScadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/auth': typeof AuthRoute
  '/chao-de-fabrica': typeof ChaoDeFabricaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/energia': typeof EnergiaRoute
  '/ia': typeof IaRoute
  '/iiot': typeof IiotRoute
  '/manutencao': typeof ManutencaoRoute
  '/mes': typeof MesRoute
  '/qualidade': typeof QualidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/scada': typeof ScadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/auth'
    | '/chao-de-fabrica'
    | '/configuracoes'
    | '/energia'
    | '/ia'
    | '/iiot'
    | '/manutencao'
    | '/mes'
    | '/qualidade'
    | '/relatorios'
    | '/scada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/auth'
    | '/chao-de-fabrica'
    | '/configuracoes'
    | '/energia'
    | '/ia'
    | '/iiot'
    | '/manutencao'
    | '/mes'
    | '/qualidade'
    | '/relatorios'
    | '/scada'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/auth'
    | '/chao-de-fabrica'
    | '/configuracoes'
    | '/energia'
    | '/ia'
    | '/iiot'
    | '/manutencao'
    | '/mes'
    | '/qualidade'
    | '/relatorios'
    | '/scada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlmoxarifadoRoute: typeof AlmoxarifadoRoute
  AuthRoute: typeof AuthRoute
  ChaoDeFabricaRoute: typeof ChaoDeFabricaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EnergiaRoute: typeof EnergiaRoute
  IaRoute: typeof IaRoute
  IiotRoute: typeof IiotRoute
  ManutencaoRoute: typeof ManutencaoRoute
  MesRoute: typeof MesRoute
  QualidadeRoute: typeof QualidadeRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ScadaRoute: typeof ScadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado': {
      id: '/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chao-de-fabrica': {
      id: '/chao-de-fabrica'
      path: '/chao-de-fabrica'
      fullPath: '/chao-de-fabrica'
      preLoaderRoute: typeof ChaoDeFabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia': {
      id: '/energia'
      path: '/energia'
      fullPath: '/energia'
      preLoaderRoute: typeof EnergiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iiot': {
      id: '/iiot'
      path: '/iiot'
      fullPath: '/iiot'
      preLoaderRoute: typeof IiotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes': {
      id: '/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof MesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scada': {
      id: '/scada'
      path: '/scada'
      fullPath: '/scada'
      preLoaderRoute: typeof ScadaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlmoxarifadoRoute: AlmoxarifadoRoute,
  AuthRoute: AuthRoute,
  ChaoDeFabricaRoute: ChaoDeFabricaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EnergiaRoute: EnergiaRoute,
  IaRoute: IaRoute,
  IiotRoute: IiotRoute,
  ManutencaoRoute: ManutencaoRoute,
  MesRoute: MesRoute,
  QualidadeRoute: QualidadeRoute,
  RelatoriosRoute: RelatoriosRoute,
  ScadaRoute: ScadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
